version: "3.9"
services:
  bot:
    image: node:lts
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./public/:/home/node/app/public
      - .:/home/node/app
    command: npm start
  http:
    image: ghcr.io/testausserveri/arm64v8-apache2:latest
    volumes:
      - ./public/:/var/www/html/
    ports:
      - 8080:80