version: "3.9"
services:
  bot:
    image: node:lts
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./public/:/home/node/app/public
      - .:/home/node/app
    command: npm start
  http:
    image: bitnami/apache:latest
    volumes:
      - ./public/:/app
    ports: 
      - 8080:8080